# Production profile configuration
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.movieflix: INFO
    org.springframework: WARN
    org.hibernate.SQL: WARN

server:
  port: 8080
  compression:
    enabled: true
