# Development profile configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.example.MovieFlix: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 8080
